image: node:12

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    - .yarn

before_script:
  - yarn config set cache-folder .yarn

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - yarn
    - wrangler
